<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.22" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.22">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.22">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MimeKit" Version="4.14.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="QuestPDF" Version="2025.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Core\HospitalManagement.Application\HospitalManagement.Application.csproj" />
    <ProjectReference Include="..\src\Core\HospitalManagement.Domain\HospitalManagement.Domain.csproj" />
    <ProjectReference Include="..\src\HospitalManagement.Infrastructure\HospitalManagement.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\admin\fonts\.DS_Store" />
    <None Include="wwwroot\admin\fonts\Roboto\.DS_Store" />
    <None Include="wwwroot\admin\images\.DS_Store" />
    <None Include="wwwroot\admin\images\auth\.DS_Store" />
    <None Include="wwwroot\admin\images\faces\.DS_Store" />
    <None Include="wwwroot\admin\js\.DS_Store" />
    <None Include="wwwroot\admin\scss\.DS_Store" />
    <None Include="wwwroot\admin\scss\components\.DS_Store" />
    <None Include="wwwroot\admin\scss\mixins\.DS_Store" />
    <None Include="wwwroot\admin\vendors\.DS_Store" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\assets\uploads\lab-results\" />
  </ItemGroup>

</Project>
